# Generated by Django 4.0.5 on 2022-06-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='账户')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('sex', models.CharField(choices=[(1, '男'), (2, '女')], max_length=4, verbose_name='性别')),
                ('phone_number', models.CharField(max_length=20, verbose_name='电话号码')),
                ('level', models.SmallIntegerField(choices=[(1, 'user'), (2, 'boss'), (3, 'admin')], default=0, verbose_name='级别')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
        ),
    ]
