# Generated by Django 4.0.5 on 2022-06-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '用户'), (2, '商家'), (3, '管理员')], default=0, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], max_length=4, verbose_name='性别'),
        ),
    ]
