# Generated by Django 4.0.5 on 2022-06-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0003_alter_users_sex_shops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='仓库名称')),
                ('address', models.CharField(max_length=32, verbose_name='仓库地址')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('category', models.SmallIntegerField(choices=[(1, '食品'), (2, '服装'), (3, '日用品'), (4, '家具'), (5, '电子设备'), (6, '纺织品'), (7, '图书'), (8, '其他')], verbose_name='商品类别')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('count', models.SmallIntegerField(verbose_name='商品数量')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app0.shops', verbose_name='店铺ID')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app0.warehouse', verbose_name='所在仓库')),
            ],
        ),
    ]
