# Generated by Django 4.0.5 on 2022-06-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0004_warehouse_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(verbose_name='成交日期')),
                ('trade_count', models.SmallIntegerField(default=1, verbose_name='数量')),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app0.items', verbose_name='商品')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app0.users', verbose_name='用户ID')),
            ],
            options={
                'unique_together': {('uid', 'iid')},
            },
        ),
    ]
