# Generated by Django 4.0.5 on 2022-06-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0007_order_price_alter_order_iid_alter_order_trade_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成交价格'),
        ),
    ]
