# Generated by Django 4.0.5 on 2022-06-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0009_alter_order_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
    ]
