# Generated by Django 4.0.5 on 2022-06-16 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0010_alter_users_phone_number_alter_users_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app0.users', verbose_name='店铺老板'),
        ),
    ]
