# Generated by Django 4.0.5 on 2022-06-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0012_alter_items_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='count',
            field=models.BigIntegerField(verbose_name='商品数量'),
        ),
    ]
